version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: admin-server-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD}  # 允许所有 IP 无密码访问（仅开发环境）
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./docker-data/postgres_data:/var/lib/postgresql/data
    networks:
      - admin-server-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  admin-server-network:
    driver: bridge
